In [2]:
a = [i for i in range(10)]
print(a)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [40]:
%%timeit
n = 10000
L = [i for i in range(n)]
A = []
for e in L:
    A.append(2*e)
    
# %%timeit 记录多次程序的平均运行时间

1.67 ms ± 47 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [42]:
import numpy as np
A = np.array([2,3,4])
B = 2*A
print(B)

[4 6 8]


In [43]:
X = np.arange(1,16).reshape(3,5)
print(X)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


## Universal Function

In [49]:
X+1
X-1
X*2
X/2
X//2
X**2
X%2
1/X
np.sin(X)
np.cos(X)
np.tan(X)
np.exp(X) 
np.power(3, X)
3**X
np.log2(X)
np.log10(X)

array([[0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ],
       [0.77815125, 0.84509804, 0.90308999, 0.95424251, 1.        ],
       [1.04139269, 1.07918125, 1.11394335, 1.14612804, 1.17609126]])

## 矩阵运算

In [50]:
A = np.array([1,2])
B = np.array([3,4])
print(A*B)
# 对应元素的运算

[3 8]


## 聚合操作
把多个数聚合成一个数

In [52]:
L = np.random.random(100)
np.sum(L)

52.427690212796925

In [54]:
np.min(L)
L.min()

0.002252812633751433

In [57]:
np.max(L)
L.max()

0.9786781351154293

In [58]:
X = np.arange(16).reshape(4, -1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [59]:
np.sum(X)

120

In [62]:
np.sum(X, axis = 0) # axis = 0 每一列的和 沿着行求和 也可以理解为压缩掉行

array([24, 28, 32, 36])

In [64]:
np.prod(X)

0

In [65]:
np.prod(X+1)

2004189184

In [66]:
np.mean(X)

7.5

In [67]:
np.median(X)

7.5

In [68]:
v = np.array([1,1,2,2,10])
np.mean(v)

3.2

In [69]:
np.median(v)  # 用中位数来统计平均薪资

2.0

In [70]:
np.percentile(L, q = 50) # 求任意百分位

0.5357402046843549

In [71]:
for percent in [0, 25, 50, 75, 100]:
    print(np.percentile(L, q = percent))

0.002252812633751433
0.2909242295708864
0.5357402046843549
0.8170335538447929
0.9786781351154293


In [72]:
np.var(L) # 求方差

0.08610262391321656

In [73]:
np.std(L) # 求标准差

0.2934324861245199